version: 2
updates:
- package-ecosystem: pip
  directory: "/"
  schedule:
    interval: daily
  open-pull-requests-limit: 10
  ignore:
  - dependency-name: sqlalchemy
    versions:
    - 1.3.23
    - 1.4.0
    - 1.4.1
    - 1.4.2
    - 1.4.3
    - 1.4.4
    - 1.4.5
    - 1.4.6
    - 1.4.7
    - 1.4.8
    - 1.4.9
  - dependency-name: phonenumbers
    versions:
    - 8.12.17
    - 8.12.18
    - 8.12.19
    - 8.12.20
  - dependency-name: regex
    versions:
    - 2021.3.17
  - dependency-name: pyflakes
    versions:
    - 2.3.0
  - dependency-name: flake8
    versions:
    - 3.8.4
    - 3.9.0
  - dependency-name: alembic
    versions:
    - 1.5.2
    - 1.5.3
    - 1.5.4
    - 1.5.5
    - 1.5.6
    - 1.5.7
  - dependency-name: pre-commit
    versions:
    - 2.10.0
    - 2.10.1
  - dependency-name: wtforms
    versions:
    - 2.3.3
  - dependency-name: flask-sqlalchemy
    versions:
    - 2.4.4
  - dependency-name: authy
    versions:
    - 2.2.6
  - dependency-name: flask
    versions:
    - 1.1.2
  - dependency-name: flask-login
    versions:
    - 0.5.0
  - dependency-name: flask-dotenv
    versions:
    - 0.1.2
