"""empty message

Revision ID: 770b2a122a82
Revises: 
Create Date: 2021-02-01 13:38:54.243356

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '770b2a122a82'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('username', sa.String(length=50), nullable=False),
    sa.Column('email', sa.String(length=120), nullable=True),
    sa.Column('authy_id', sa.String(length=12), nullable=True),
    sa.Column('pw_hash', sa.String(length=50), nullable=True),
    sa.Column('is_authenticated', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('username'),
    sa.UniqueConstraint('username')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('users')
    # ### end Alembic commands ###
